version: '3.8'

volumes:
  node_modules:
    driver: local
services:
  nodejs:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: 'nodejs'
    volumes:
      - ./:/mnt
      - node_modules:/app/node_modules
    tty: true
    working_dir: /mnt/
    command: npm run start
